# Generated by Django 5.2.8 on 2025-11-19 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, default=list, size=None)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
