# Generated by Django 5.2.8 on 2025-11-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
